### ISSUE TITLE
Go 1.11 is now available on App Engine

### ISSUE THREAD

**Issue by peterhellberg** [marcusolsson/cd-demo#1]
There is a new runtime on GAE for Go 1.11 (`runtime: go111`) and it supports idiomatic Go projects (`main` package and function, vendoring, unrestricted network calls, etc.)

## Links
 - https://cloud.google.com/blog/products/application-development/go-1-11-is-now-available-on-app-engine
 - https://cloud.google.com/appengine/docs/standard/go111/

**Comment by marcusolsson** [comment]
Good job finding my little demo app! ;)
